#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 6cec28fb-fa1a-4183-bec1-66de858dbb14
# Source File: C:\Users\Muhammad Suhail\Documents\SAPIEN\PowerShell Studio\Files\Excel Approval GUI.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       11/2/2021 6:52 PM
     Generated by:       Muhammad Suhail
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Excel_Approval_GUI_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$button5 = New-Object 'System.Windows.Forms.Button'
	$buttonBatch3 = New-Object 'System.Windows.Forms.Button'
	$button3 = New-Object 'System.Windows.Forms.Button'
	$button2 = New-Object 'System.Windows.Forms.Button'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$button1_Click={
		#TODO: Place custom script here
		
	}
	
	$button2_Click={
		#TODO: Place custom script here
		
	}
	
	$button3_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonBatch3_Click={
		#TODO: Place custom script here
		
	}
	
	$button5_Click={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$button5.remove_Click($button5_Click)
			$buttonBatch3.remove_Click($buttonBatch3_Click)
			$button3.remove_Click($button3_Click)
			$button2.remove_Click($button2_Click)
			$button1.remove_Click($button1_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($statusbar1)
	$form1.Controls.Add($button5)
	$form1.Controls.Add($buttonBatch3)
	$form1.Controls.Add($button3)
	$form1.Controls.Add($button2)
	$form1.Controls.Add($button1)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '284, 261'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# statusbar1
	#
	$statusbar1.Location = '0, 239'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '284, 22'
	$statusbar1.TabIndex = 5
	$statusbar1.Text = 'No task is running at the moment'
	#
	# button5
	#
	$button5.Location = '12, 158'
	$button5.Name = 'button5'
	$button5.Size = '75, 23'
	$button5.TabIndex = 4
	$button5.Text = 'button5'
	$button5.UseCompatibleTextRendering = $True
	$button5.UseVisualStyleBackColor = $True
	$button5.add_Click($button5_Click)
	#
	# buttonBatch3
	#
	$buttonBatch3.Location = '12, 129'
	$buttonBatch3.Name = 'buttonBatch3'
	$buttonBatch3.Size = '75, 23'
	$buttonBatch3.TabIndex = 3
	$buttonBatch3.Text = 'Batch-3'
	$buttonBatch3.UseCompatibleTextRendering = $True
	$buttonBatch3.UseVisualStyleBackColor = $True
	$buttonBatch3.add_Click($buttonBatch3_Click)
	#
	# button3
	#
	$button3.Location = '12, 100'
	$button3.Name = 'button3'
	$button3.Size = '75, 23'
	$button3.TabIndex = 2
	$button3.Text = 'button3'
	$button3.UseCompatibleTextRendering = $True
	$button3.UseVisualStyleBackColor = $True
	$button3.add_Click($button3_Click)
	#
	# button2
	#
	$button2.Location = '12, 71'
	$button2.Name = 'button2'
	$button2.Size = '75, 23'
	$button2.TabIndex = 1
	$button2.Text = 'button2'
	$button2.UseCompatibleTextRendering = $True
	$button2.UseVisualStyleBackColor = $True
	$button2.add_Click($button2_Click)
	#
	# button1
	#
	$button1.Location = '12, 42'
	$button1.Name = 'button1'
	$button1.Size = '75, 23'
	$button1.TabIndex = 0
	$button1.Text = 'button1'
	$button1.UseCompatibleTextRendering = $True
	$button1.UseVisualStyleBackColor = $True
	$button1.add_Click($button1_Click)
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-Excel_Approval_GUI_psf | Out-Null
